SOLANA_RPC_ENDPOINT = "https://solana-mainnet.core.chainstack.com/d70aa036553f9b407feda39c2d88a5f0"

REDIS_HOST = "localhost"
REDIS_PORT = 6379

REDIS_METADATA_KEY = 'snapshot:metadata:%s:%s'
POOLS_CURRENT_STATE_DICT_REDIS_KEY = 'snapshot:%s:%s'

LOG_MAIN_FOLDER = 'LogFolder/'

ORCA_CLMM_PROGRAM_ID = 'whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc'
METEORA_DLMM_PROGRAM_ID = 'LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo'
MAX_BIN_PER_ARRAY_DLMM = 70

RAYDIUM_CLMM_PROGRAM_ID = 'CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK'
